In [8]:
import numpy as np

import os
from os.path import  join

In [9]:
data= np.load("./npy_data/20_clean/20_205_20-205-0004.npy")
type(data)

numpy.ndarray

In [10]:
data.size

70000

In [2]:
[x[0] for x in os.walk("D:\test_neurolab\train\clean")]

[]

In [ ]:
output = [dI for dI in os.listdir('foo') if os.path.isdir(os.path.join('foo',dI))]

In [33]:
st = 0 
clean_data = []
clead_data_sizes = []
clead_data_shape = []
clean_data_path = "D://test_neurolab//train//clean"
for folder in os.listdir(clean_data_path):
    for file in os.listdir(join(clean_data_path, folder)):
        #print(join(clean_data_path, folder, file))
        data = np.load(join(clean_data_path, folder, file))
        clean_data.append(data)
        clead_data_sizes.append(data.size)
        clead_data_shape.append(data.shape)
        #print(data.size)
        #st += 1
    #if st> 35: break

In [20]:
clead_data_sizes[:10]

[77280, 52640, 33120, 77920, 69760, 72880, 77760, 72400, 83280, 68800]

In [34]:
clead_data_shape[:10]

[(966, 80),
 (658, 80),
 (414, 80),
 (974, 80),
 (872, 80),
 (911, 80),
 (972, 80),
 (905, 80),
 (1041, 80),
 (860, 80)]

In [81]:
for shape in clead_data_shape:
    if shape[1] != 80:
        print ("fff")

In [22]:
noisy_data = []
noisy_data_sizes = []
noisy_data_path = "D://test_neurolab//train//noisy"
for folder in os.listdir(noisy_data_path):
    for file in os.listdir(join(noisy_data_path, folder)):
        data= np.load(join(noisy_data_path, folder, file))
        noisy_data.append(data)
        noisy_data_sizes.append(data.size)

In [19]:
clead_data_sizes == noisy_data_sizes

True

In [32]:
clean_data[1].shape

(658, 80)

In [35]:
a = np.arange(10).reshape(2, 5)

In [36]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
ixgrid = np.ix_([0, 1], range(2,5))
ixgrid

(array([[0],
        [1]]), array([[2, 3, 4]]))

In [45]:
ex_data = clean_data[1]

In [51]:
ex_data.shape[0]

658

In [80]:
ixgrid = np.ix_(range(125), range(80))
ex_data[ixgrid]

array([[ 0.659 ,  0.661 ,  0.651 , ..., -0.4233, -0.3564, -0.3452],
       [ 0.657 ,  0.6147,  0.637 , ..., -0.4607, -0.3926, -0.401 ],
       [ 0.658 ,  0.5913,  0.621 , ..., -0.4739, -0.4219, -0.4275],
       ...,
       [ 0.639 ,  0.6084,  0.6504, ...,  0.383 ,  0.3877,  0.3706],
       [ 0.6445,  0.6157,  0.6895, ...,  0.392 ,  0.385 ,  0.3386],
       [ 0.643 ,  0.5596,  0.532 , ...,  0.4072,  0.3894,  0.2827]],
      dtype=float16)

In [66]:
ex_data.shape

(658, 80)

In [135]:
for i in range(ex_data.shape[0]//80 + 1):
    if (80*(i+1)-1 < ex_data.shape[0]):
        print(80*i, 80*(i+1)-1)
        ixgrid = np.ix_(range(80*i, 80*(i+1)), range(80))
        sample = ex_data[ixgrid]
        print(ex_data[ixgrid].shape)
        #print(ex_data[ixgrid])
    else:
        #zero_matrix = np.zeros((80,80))
        print("fufu",ex_data.shape[0])
        ixgrid = np.ix_(range(80*i, ex_data.shape[0]), range(80))
        print(ex_data[ixgrid].shape)
        #print(ex_data[ixgrid])
        #print(np.add(ex_data[ixgrid], (80,80),'reflect'))
        pad_matrix = np.pad(ex_data[ixgrid], ((0, 80 - ex_data[ixgrid].shape[0]), (0, 0)), 'median')
        print(pad_matrix.shape)

0 79
(80, 80)
80 159
(80, 80)
160 239
(80, 80)
240 319
(80, 80)
320 399
(80, 80)
400 479
(80, 80)
480 559
(80, 80)
560 639
(80, 80)
fufu 658
(18, 80)
(80, 80)


In [159]:
def get_rect_windows(mel, debug = False):
    if (debug): print("mel size", mel.shape)
    windows = []
    for i in range(mel.shape[0]//80 + 1):
        if (80*(i+1)-1 < mel.shape[0]):
            if (debug): print("current size", 80*i, 80*(i+1)-1)
                
            ixgrid = np.ix_(range(80*i, 80*(i+1)), range(80))
            sample = mel[ixgrid]
            windows.append(sample)
            
            if (debug): print(mel[ixgrid].shape)
        elif(80 - (80*(i+1)-1 - mel.shape[0]) > 30): 
            
            if (debug): print("current size", 80*i, 80*(i+1)-1)
            ixgrid = np.ix_(range(80*i, mel.shape[0]), range(80))
            if (debug): print(mel[ixgrid].shape)                
            pad_matrix = np.pad(mel[ixgrid], ((0, 80 - mel[ixgrid].shape[0]), (0, 0)), 'median')
            if (debug): print(pad_matrix.shape) 
            windows.append(pad_matrix)
        else:
            if (debug): print("not enough real data left", 80 - (80*(i+1)-1 - mel.shape[0]))
    return windows
a = get_rect_windows(ex_data, debug = True)

mel size (658, 80)
current size 0 79
(80, 80)
current size 80 159
(80, 80)
current size 160 239
(80, 80)
current size 240 319
(80, 80)
current size 320 399
(80, 80)
current size 400 479
(80, 80)
current size 480 559
(80, 80)
current size 560 639
(80, 80)
not enough real data left 19


In [140]:
colors = ['red', 'blue', 'green']
colors_1 = ['red', 'blue', 'green']
colors.extend(colors_1)
colors

['red', 'blue', 'green', 'red', 'blue', 'green']

In [160]:
clean_data_wind = []
for mel in clean_data:
    new_windows = get_rect_windows(mel)
    clean_data_wind.extend(new_windows)

In [163]:
ixgrid = np.ix_(range(80), range(80))

In [165]:
clean_data[0][ixgrid] == clean_data_wind[0]

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [167]:
clean_data_wind[0].shape

(80, 80)

In [168]:
for w in clean_data_wind:
    if w.shape != (80, 80):
        print("dsd")

In [166]:
noisy_data_wind = []
for mel in noisy_data:
    new_windows = get_rect_windows(mel)
    noisy_data_wind.extend(new_windows)